repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.0.1
      hooks:
          - id: check-yaml
          - id: end-of-file-fixer
    - repo: https://github.com/pocc/pre-commit-hooks
      rev: v1.1.1
      hooks:
          - id: clang-format
            args: [--style=Google]
          - id: clang-tidy
            args: [-checks=clang-diagnostic-return-type]
          - id: oclint
            args: [-enable-clang-static-analyzer, -enable-global-analysis]
          - id: uncrustify
          - id: cppcheck
            args: [--enable=all]
    - repo: https://github.com/psf/black
      rev: 21.8b0
      hooks:
          - id: black
